### ISSUE TITLE
HI. Wrong icons

### ISSUE THREAD

**Issue by martsrzx91** [Grifonice99/crafting-efficiency-2#1]
I am on latest mod version updating from previous and after launching save it removed previous researches as said in changelog, but seems like some icons are wrong
![image](https://github.com/user-attachments/assets/2e4c93da-4a36-4240-995f-1dfe0f88ea78)

**Comment by Grifonice99** [comment]
Bug fixed, Good Game.

**Comment by martsrzx91** [comment]
;)
